### ISSUE TITLE
Smart Bag Killer

### ISSUE THREAD

**Issue by Nofayro2** [bestnaf/ARS#8]
●Those are the steps for smart bags killer:

1. HR get triggered only one time after we reached LS in any pair and the loss higher than 4% (means the Wallet Allocation higher than 4% and not the UNPNL for each pair) . And ARS must reduce the wallet Allocation to 2%.

2. ARS must set HR false after his job and our SL must place loss-order at 4% from wallet size if the bag decided to grow again.

3. MAX_LOSS got triggered directly if the loss higher than 5% and lower than 6% from wallet size in bad situations.

Simply:
▪︎if the loss 4% or higher do this:
>>Reduce it until 2% from wallet size and set HR false then set SL 4% from wallet size.

▪︎trigger Max Loss:
 >>if the wallet Allocation is 5% and lower than 6%

Those are just numbers and the user can select them according to his risk management. 
For example we can set our Max loss from wallet Allocation 5%, 6%, 8%, 10%. It depends on the trading style.

So we are doing step by step and killing the bags slowly but the maximum loss is 6% or 5% from wallet size in very very bad cases like LTC....

So we are focusing here on the wallet Allocation and not  the UNPNL for each pair because it's gonna kill the whole wallet if use UNPNL. 
Imagine you are trading with 8 pairs.  
Max Loss gonna be higher than 40% from wallet size if we use UNPNL as indicator or whatever.

**Comment by bestnaf** [comment]
Wil be inluded in 9.6.2
PAIR.settings.SBK = True (default False)
PAIR.settings.SBK_SL_LIM = 4 (default) - will trigger the partial HR for all negative uPNL positins if wallet allocation > 4% untill it frops to SBK-SL_LIM / 2. Then it will close all negative uPNL positins sompletely if wallet allocation back to 4% again
for point #3 use this:
PAIR.settings.WA_SL = True (default False)
PAIR.settings.WA_SL_LIM = 6 (default 90) - will close all positions is Wallet allocation above this value
